### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by xzc1278815766** [fellow-me/hrm#2]
您好，我在运行hrm项目的时候在登录页面出现输入用户密码无法跳转的情况

**Comment by fellow-me** [comment]
你可以说说具体情况吗，是密码的问题，还是其他，你看看数据库是否正常

**Comment by wsws98** [comment]
您好，大佬，想在自己电脑上跑下你的项目，您可不可以出一期视频教教我们这些小白怎么跑啊，感激不尽！

**Comment by A125-q** [comment]
我想问一下就是导入文件，是不是导入外面的这个大文件，里面的Excel表格这些是不是要拿出来，还是只导入两个文件夹呀

**Comment by A125-q** [comment]
@fellow-me 我想问一下就是导入文件，是不是导入外面的这个大文件，里面的Excel表格这些是不是要拿出来，还是只导入两个文件夹呀

**Comment by fellow-me** [comment]
这两两个excel表是我提供的导入样例，你可以放在项目目录下，也可以放在任何文件夹下，导入只需导入excel表就行

**Comment by fellow-me** [comment]
@A125-q

**Comment by A125-q** [comment]
@fellow-me 
![微信截图_20240709084521](https://github.com/fellow-me/hrm/assets/175070172/03c78db1-ba3b-4f5d-8b63-c9522c1686aa)
我导入文件直接导入这个大文件到idea里面吗

**Comment by fellow-me** [comment]
@A125-q 你连readme都不看吗？

**Comment by A125-q** [comment]
@fellow-me 看了，我不太会改

**Comment by A125-q** [comment]
@fellow-me 看了，我不太会改

**Comment by A125-q** [comment]
![微信截图_20240709100920](https://github.co@fellow-me /fellow-me/hrm/assets/175070172/e962bd81-cdf8-41ff-8935-15ddb90f11f7)
@fellow-me 这里为啥是报错的

**Comment by A125-q** [comment]
@fellow-me 依赖里面没有serial

**Comment by fellow-me** [comment]
![image](https://github.com/fellow-me/hrm/assets/58590342/2461f7d4-e5bb-47e7-b60a-c138d6ea0b0c)
你再截一下图

**Comment by fellow-me** [comment]
@A125-q

**Comment by A125-q** [comment]
![微信截图_20240709101838](https://github.com/fellow-me/hrm/assets/175070172/31095366-8df4-419b-b19a-0654b76c02ff)
![微信截图_20240709100920](https://github.com/fellow-me/hrm/assets/175070172/3569b349-203b-4401-8eda-f18f182f6d7e)

**Comment by A125-q** [comment]
![微信截图_20240709102033](https://github.com/fellow-me/hrm/assets/175070172/6555825c-025c-45ca-93c1-4a4edf283892)

**Comment by fellow-me** [comment]
@A125-q 你导入相应依赖就行，这个在网上搜

**Comment by A125-q** [comment]
@fellow-me 这个要修改吗toList()

**Comment by fellow-me** [comment]
@A125-q 把这个方法删了

**Comment by A125-q** [comment]
@fellow-me Serial这个依赖还是没有

**Comment by A125-q** [comment]
@fellow-me 
![Uploading 微信截图_20240709151349.png…]()

**Comment by A125-q** [comment]
@fellow-me 不是执行那个吗？

**Comment by fellow-me** [comment]
@A125-q 
![image](https://github.com/fellow-me/hrm/assets/58590342/a8568fa8-608e-42e5-acb8-ac7d545d6c41)

**Comment by A125-q** [comment]
![Uploading 微信截图_20240709151349.png…]()

**Comment by A125-q** [comment]
![Uploading 微信截图_20240709151349.png…]()

**Comment by A125-q** [comment]
![微信截图_20240709152922](https://github.com/fellow-me/hrm/assets/175070172/bb32ee68-73b7-45d0-9def-83eff328887f)

**Comment by fellow-me** [comment]
@A125-q 简单问题自己到网上去搜

**Comment by A125-q** [comment]
@fellow-me 就是因为搜了还是不会来问哥
