### ISSUE TITLE
这边前端是不是代码没有上传全

### ISSUE THREAD

**Issue by yangjiashengYJS** [fellow-me/hrm#3]
我这前端代码下载下来只有登录  和首页

**Comment by fellow-me** [comment]
代码是全的，记得新建一个数据库，把sql文件导入，这个菜单显示是根据当所登录的用户的角色来显示的，前后端都要启动。具体问题可以看文档，应该很详细了。

**Comment by yangjiashengYJS** [comment]
@fellow-me 好的谢谢  是我这边搞错了   第一次登录的时候  用户菜单没有加载 需要退出重新登录
