### ISSUE TITLE
为什么登陆成功后没有系统管理和权限管理两个模块？

### ISSUE THREAD

**Issue by Ikeltis** [fellow-me/hrm#31]
请问这是哪里部署出现了问题？
![image](https://github.com/fellow-me/hrm/assets/38709146/5744dead-39ca-4133-95a0-4a051cf6235d)

**Comment by fellow-me** [comment]
有可能sql文件没导入完整

**Comment by Ikeltis** [comment]
> 有可能sql文件没导入完整

重新clone项目好了，谢谢！
